#!/usr/bin/env python3
"""
This script installs the cpr-indoornav.service systemd jobs, used for
starting IndoorNav.
"""

import argparse
import getpass
import cpr_indoornav_base.installation
import os
import robot_upstart
import sys

from catkin.find_in_workspaces import find_in_workspaces

parser = argparse.ArgumentParser()
parser.add_argument('-a','--ip-address', metavar='IP_ADDR', type=str, action='store', dest='ip_address', help='IP address of the IndoorNav backpack. Default: 10.252.252.1', default='10.252.252.1')
parser.add_argument('-u','--username', metavar='USER', type=str, action='store', dest='username', help='Login name for the IndoorNav backpack. Default: administrator', default='administrator')
args = parser.parse_args()

if getpass.getuser() == 'root':
    print("ERROR: This script cannot be run as root")
    sys.exit(1)

backpack_ip = args.ip_address
remote_user = args.username
local_user = getpass.getuser()

cpr_indoornav_base.installation.create_indoornav_service('jackal', local_user, remote_user, backpack_ip)
