#!/bin/bash

# update /etc/ros/setup.bash with the additional envars
echo "export INDOORNAV_ENABLE_DOCKING=true   # enable/disable indoornav docking" | sudo tee -a /etc/ros/setup.bash
echo "export DOCK_DISTANCE=-0.2" | sudo tee -a /etc/ros/setup.bash
echo "export UNDOCK_DISTANCE=2.0" | sudo tee -a /etc/ros/setup.bash
